"""initial schema

Revision ID: 549f2049e14b
Revises: 
Create Date: 2025-08-03 13:29:34.328159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549f2049e14b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=False),
    sa.Column('start', sa.String(length=20), nullable=False),
    sa.Column('end', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('start', sa.String(length=20), nullable=False),
    sa.Column('end', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('tech',
               existing_type=sa.TEXT(),
               type_=sa.PickleType(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('tech',
               existing_type=sa.PickleType(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###
